import { User } from "firebase/auth";

export interface CPUScore {
	you: number;
	cpu: number;
}

export type UserName = string | undefined;

export type UID = User["uid"];
export type Email = NonNullable<User["email"]> | undefined;

export enum Collections {
	score = "score",
}

export interface UserInformation {
	score: CPUScore;

	/**
	 * User id of the user. This id is generated by the firebase.
	 */
	uid: UID;

	/**
	 * User name of the user.
	 */
	userName: UserName;
	photoUrl: User["photoURL"];

	/**
	 * Email id of the user.
	 */
	email: Email;
}
